[package]
name = "schule"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
rev_lines = "0.2.1"
termsize = "0.1.6"
